
instructions = 

"""

The CSV files to be ran must be found in the same
directory as the sorting algorithms. 

To run the algorithm, run <sorting_algorithm> <csv_file>

For example, to sort an input file named 'test_input.csv' using HeapSort.py, type:
'HeapSort.py test_input'


"""

[[student]]
name = "WenChao Chen"
utor = "chenw130"
nmbr = "1002475083"


