
instructions = 

"""
In the directory of the python script:

1. chmod +x influence.py
2. influence.py <txt_file.txt> <Deadline Constraint>

ensure that a .txt file is in the same directory as the python script.

For example: influence.py facebook_small.txt 3

The program will output the TOP-1 INFLUENCER node, spread, and compute time given the deadline constraint provided.
Please note that TOP-2 INFLUENCER bonus question was not attempted. 

"""

[[student 1]]		
name = "WenChao Chen"
utor = "chenw130"
nmbr = "1002475083"

[[student 2]]
name = "Daniel Fan"
utor = "fandani1"
nmbr = "1003154061"
